### ISSUE TITLE
Tilde syntax `x ~ foo` looks for `@trace` in the caller's namespace

### ISSUE THREAD

**Issue by bzinberg** [probcomp/Gen.jl#222] opened 2020-03-31 17:45 UTC
Example:
```julia
Gen.@gen function f()
  x ~ Gen.normal(0, 1)
end
# ERROR: LoadError: UndefVarError: @trace not defined
```
I think this is a bug in the macro escaping.

**Comment by bzinberg** [comment] 2020-03-31 17:52
oh jk, it's actually that the `@trace` macro is being called incorrectly.  Or maybe both?  Sending fix

**Comment by ztangent** [comment] 2020-03-31 17:52
Yeah I think [this is the function](https://github.com/probcomp/Gen/blob/964d8a96205de6bb13e69f13eec7eaff7906c952/src/dsl/dsl.jl#L73) that needs to be fixed by prefixing each `@trace` with `Gen.`

```julia
function desugar_tildes(expr)
    MacroTools.postwalk(expr) do e
        if MacroTools.@capture(e, {*} ~ rhs_)
            :(@trace($rhs))
        elseif MacroTools.@capture(e, {addr_} ~ rhs_)
            :(@trace($rhs, $(addr)))
        elseif MacroTools.@capture(e, lhs_ ~ rhs_)
            addr_expr = address_from_expression(lhs)
            :($lhs = @trace($rhs, $(addr_expr)))
        else
            e
        end
    end
end
```

**Comment by bzinberg** [comment] 2020-03-31 17:55
@ztangent, see https://github.com/probcomp/Gen/pull/223 :slightly_smiling_face: 

I think what should be happening is that `trace` (as a function on ASTs) should be called at macro expansion time, from within Gen's internals.  Instead, the desugarer was punting the `@trace`ing to the caller, which actually worked if the caller happened to have `@trace` in their namespace, but was not the intended logic.

**Comment by bzinberg** [comment] 2020-03-31 17:58
Hm, a unit test is now failing probably due to #223 not doing some escaping that it should be doing.  I'll try to figure it out :)

**Comment by ztangent** [comment] 2020-03-31 18:21
As mentioned in #223, I think there needs to be some care to make sure the fix for this works with the DML and the SML. The fix I suggested in my comment above (i.e. prefixing `@trace` by `Gen`) should work for the DML, but it most likely will not work with the SML because the SML parser tries to match `@trace` expressions, and so will fail to match `Gen.@trace`.

In fact, even without tilde syntax, I think if you do `import Gen` instead of `using Gen`, the SML will fail for the following function (when it should work):
```julia
Gen.@gen function f()
  x = Gen.@trace(Gen.normal(0, 1), :x)
end
```
but work for the following function (when it should fail):
```julia
Gen.@gen function f()
  x = @trace(Gen.normal(0, 1), :x)
end
```
i.e. the SML doesn't obey the standard scoping rules.

**Comment by ztangent** [comment] 2020-03-31 18:27
I think probably the most principled way (in terms of consistency with standard Julia scoping rules) to fix this is to:

1. Add the `Gen.` prefix to `@trace` in the `desugar_tildes` function -- this should ensure the DML always works.
2. Pass the calling `__module__` from the the `@gen` macro all the way down to the various SML parsing functions, so that can selectively match either `@trace`, `Gen.@trace`, or both, depending on whether `@trace` exists in the calling `__module__`.
3. Do the above for `@param` in the SML as well.

**Comment by alex-lew** [comment] 2020-03-31 18:38
@bzinberg, good catch, and @ztangent, good analysis!

I think what we're running up against is that it doesn't make a whole lot of sense that `@trace` is a macro in the static DSL, because it is never actually macroexpanded -- instead, it's syntax that the `@gen` macro explicitly looks for. 

Long-term, I wonder if it makes sense to phase out `@trace` from the static DSL (because it never actually resolves to a Julia binding) and just have the `~` syntax. (Implementation-wise, `~` could replace with `Gen.@trace`, and static DSL could look for `Gen.@trace`.) I think that `@trace` still plays an important role in the dynamic DSL, ensuring that the `@trace` calls in nested generative function definitions are properly resolved.

**Comment by bzinberg** [comment] 2020-03-31 18:48
> I think probably the most principled way (in terms of consistency with standard Julia scoping rules) to fix this is to:
> 
> 1. Add the `Gen.` prefix to `@trace` in the `desugar_tildes` function -- this should ensure the DML always works.
> 
> 2. Pass the calling `__module__` from the the `@gen` macro all the way down to the various SML parsing functions, so that can selectively match either `@trace`, `Gen.@trace`, or both, depending on whether `@trace` exists in the calling `__module__`.
> 
> 3. Do the above for `@param` in the SML as well.

@ztangent, definitely not an expert but my thoughts are:

I think 1. assumes the caller has a module called `Gen` in their namespace, which I think is not necessary.
For 2., [Edit: whoops, I misread it.]

I don't think there is a principled reason to assume that the caller has the `@trace` macro, or the Gen module, available under some specific name.

I currently believe the most principled solution (for the dynamic DSL) is:
https://github.com/probcomp/Gen/blob/09a86c01042a6f449059d2d96b1f08b920b29564/src/dsl/dsl.jl#L73-L90

**Comment by alex-lew** [comment] 2020-03-31 18:51
> I think 1. assumes the caller has a module called Gen in their namespace, which I think is not necessary.

I think in Julia, you can’t import something without getting its name?

**Comment by bzinberg** [comment] 2020-03-31 18:53
> > I think 1. assumes the caller has a module called Gen in their namespace, which I think is not necessary.
> 
> I think in Julia, you can’t import something without getting its name?

What if the user imports a package `Foo` that depends on Gen?  My understanding is that `Foo.Gen` will exist for them but `Gen` will not.

**Comment by ztangent** [comment] 2020-03-31 19:59
@bzinberg that solution looks like it should work for the DML, but I think it'll still break support for the tilde syntax in the SML :/

**Comment by bzinberg** [comment] 2020-03-31 20:10
Hmm yeah... I think similar to what @alex-lew suggested in https://github.com/probcomp/Gen/issues/222#issuecomment-606801429, it might make sense to replace `@trace` with tilde syntax completely in the static modelling language.  I think the `@trace` syntax is misleading, because it makes it look like `@trace` is a macro but it's not -- it's a keyword that is specific to the modelling language, and has semantics similar to `@trace` in the DML (which is a macro).  The complaint I have with this pun is that `@trace` in the SML cannot be referred to by a qualified name like `Foo.@trace` (and in fact is not imported from anywhere, it's syntax) -- it has to be referred to by exactly the expression `@trace`.

**Comment by ztangent** [comment] 2020-03-31 20:13
Yeah I agree that the issue is with the SML, but removing support for `@trace` would be a breaking change for a lot of existing code (including some of my own). I think this warrants a longer discussion with @marcoct?

**Comment by bzinberg** [comment] 2020-03-31 20:15
@ztangent yes, I definitely did not mean to imply an overly hasty migration strategy -- or even a commitment to do the migration at all.  I'm considering us to be at the stage of coming to consensus about what the ideal long-term resolution is, independent of whether or how much time we can afford to invest in moving toward that ideal.

**Comment by ztangent** [comment] 2020-03-31 20:20
Here's a possible alternative that preserves `@trace` support in the SML. Since `@trace` macroexpands to either a `traceat` call or a `splice` call (see below), we could make the SML parser match those expressions instead. This would also nicely allow it catch and throw errors on any `splice` call, since splicing is currently not supported by the SML. (With the SML refactor, splicing is already caught at parse time, but only by checking that `@trace` calls don't have a supplied address).

https://github.com/probcomp/Gen/blob/09a86c01042a6f449059d2d96b1f08b920b29564/src/dynamic/dynamic.jl#L63-L79

**Comment by bzinberg** [comment] 2020-03-31 21:28
@ztangent nice!  This is orthogonal to the fix in the DML, right?

**Comment by ztangent** [comment] 2020-03-31 21:43
@bzinberg You mean orthogonal to the fix you've already made for the DML? Well, it would rely on the macroexpansion being done in desugar_tildes, so not exactly orthogonal. It would also require macroexpanding any direct `@trace` calls (and ideally `@param` calls too) in the static function body, before passing the function body to `make_static_gen_function`.

**Comment by bzinberg** [comment] 2020-04-02 17:35
@ztangent, do you think this is a reasonable complete fix?:

1. Change `@trace` as in https://github.com/probcomp/Gen/pull/223, so that macro expansion works regardless of what names exist in the caller's scope.
2. Make the changes you suggested in https://github.com/probcomp/Gen/issues/222#issuecomment-606852924, and document them as: "In the SML, `traceat` and `splice` are keywords; in the DML, they are functions."
3. Change `make_static_gen_function` as you suggested in https://github.com/probcomp/Gen/issues/222#issuecomment-606892981

**Comment by ztangent** [comment] 2020-04-02 18:59
I think that should work, yup! Happy to review any of the changes made to
the static parser. Also, if this is going to happen, I suggest reorganizing
the code so that `@param` and `@trace` are defined in dsl.jl, since they will
now be shared by both the static and dynamic modeling languages.

(edited to remove my email etc from edit history.)

**Comment by ztangent** [comment] 2020-04-02 19:02
Hmm, I just realized that splice is also defined in Base if I'm
not mistaken... And in general users would need to make sure they don't
define their own traceat and splice functions when using the static
modeling language.

Edit: `Base.splice!` is defined, but `Base.splice` is not.

**Comment by bzinberg** [comment] 2020-04-07 00:52
> in general users would need to make sure they don't define their own traceat and splice functions when using the static modeling language.

That's the case for any reserved word, right?  I think users expect that (like in Python you can't say `def = 7`).  Adding reserved words of some sort to the SML sounds reasonable to me, since they really are part of the syntax.

**Comment by bzinberg** [comment] 2020-04-07 00:55
@ztangent

> I think that should work, yup!

Great :+1: 

> Happy to review any of the changes made to the static parser.

Would you be up for implementing these changes?  You could push commits to https://github.com/probcomp/Gen/pull/223 so that we have one combined fix and then we can review it together.

**Comment by bzinberg** [comment] 2020-04-07 00:57
BTW, to your point about reserved words, yeah, I think it would be a good idea to use something less high-frequency-word than `splice` as the reserved word -- perhaps something like `Gen_splice`.

**Comment by ztangent** [comment] 2020-04-07 02:59
@bzinberg yeah, or maybe `spliceat`, in keeping with `traceat`!

And yeah, I can make those changes -- but it may have to wait till next week when I'm a little less busy!

**Closed as completed** 2020-06-20 19:58 UTC
Labels: bug
